-- Paper Desk core schema. Written to run on both real PostgreSQL and H2
-- (MODE=PostgreSQL).

CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    display_name  VARCHAR(120) NOT NULL,
    role          VARCHAR(20)  NOT NULL,
    created_at    TIMESTAMP    NOT NULL,
    CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE TABLE scenarios (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(80)  NOT NULL,
    description  VARCHAR(400),
    seed         BIGINT        NOT NULL,
    acceleration NUMERIC(12,2) NOT NULL,
    params_json  TEXT          NOT NULL,
    CONSTRAINT uq_scenarios_name UNIQUE (name)
);

CREATE TABLE scenario_sessions (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scenario_id      BIGINT        NOT NULL,
    cohort_id        BIGINT,
    state            VARCHAR(20)   NOT NULL,
    sim_start        TIMESTAMP     NOT NULL,
    current_sim_time TIMESTAMP     NOT NULL,
    acceleration     NUMERIC(12,2) NOT NULL,
    created_at       TIMESTAMP     NOT NULL,
    CONSTRAINT fk_sess_scenario FOREIGN KEY (scenario_id) REFERENCES scenarios(id)
);

CREATE TABLE instruments (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id         BIGINT        NOT NULL,
    symbol             VARCHAR(80)   NOT NULL,
    name               VARCHAR(160)  NOT NULL,
    instrument_type    VARCHAR(20)   NOT NULL,
    underlying_id      BIGINT,
    strike             NUMERIC(19,6),
    expiry_date        DATE,
    call_put           VARCHAR(4),
    contract_size      NUMERIC(19,4) NOT NULL,
    initial_margin     NUMERIC(19,4),
    maintenance_margin NUMERIC(19,4),
    notional           NUMERIC(19,2),
    fixed_rate         NUMERIC(12,8),
    pay_freq_months    INTEGER,
    term_months        INTEGER,
    active             BOOLEAN       NOT NULL,
    CONSTRAINT fk_instr_session FOREIGN KEY (session_id) REFERENCES scenario_sessions(id),
    CONSTRAINT fk_instr_under FOREIGN KEY (underlying_id) REFERENCES instruments(id),
    CONSTRAINT uq_instr_symbol UNIQUE (session_id, symbol)
);

CREATE TABLE accounts (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT        NOT NULL,
    session_id       BIGINT        NOT NULL,
    cash_balance     NUMERIC(19,4) NOT NULL,
    margin_held      NUMERIC(19,4) NOT NULL,
    starting_balance NUMERIC(19,4) NOT NULL,
    created_at       TIMESTAMP     NOT NULL,
    CONSTRAINT fk_acct_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_acct_session FOREIGN KEY (session_id) REFERENCES scenario_sessions(id),
    CONSTRAINT uq_acct_user_session UNIQUE (user_id, session_id)
);

CREATE TABLE orders (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id      BIGINT        NOT NULL,
    instrument_id   BIGINT        NOT NULL,
    side            VARCHAR(4)    NOT NULL,
    order_type      VARCHAR(10)   NOT NULL,
    limit_price     NUMERIC(19,6),
    qty             NUMERIC(19,4) NOT NULL,
    status          VARCHAR(12)   NOT NULL,
    view_context    VARCHAR(10),
    reject_reason   VARCHAR(200),
    placed_sim_time TIMESTAMP     NOT NULL,
    CONSTRAINT fk_ord_account FOREIGN KEY (account_id) REFERENCES accounts(id),
    CONSTRAINT fk_ord_instr FOREIGN KEY (instrument_id) REFERENCES instruments(id)
);

CREATE TABLE fills (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id      BIGINT        NOT NULL,
    price         NUMERIC(19,6) NOT NULL,
    qty           NUMERIC(19,4) NOT NULL,
    fill_sim_time TIMESTAMP     NOT NULL,
    CONSTRAINT fk_fill_order FOREIGN KEY (order_id) REFERENCES orders(id)
);

CREATE TABLE positions (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id        BIGINT        NOT NULL,
    instrument_id     BIGINT        NOT NULL,
    qty               NUMERIC(19,4) NOT NULL,
    avg_price         NUMERIC(19,6) NOT NULL,
    realized_pnl      NUMERIC(19,4) NOT NULL,
    last_settle_price NUMERIC(19,6),
    opened_sim_time   TIMESTAMP     NOT NULL,
    CONSTRAINT fk_pos_account FOREIGN KEY (account_id) REFERENCES accounts(id),
    CONSTRAINT fk_pos_instr FOREIGN KEY (instrument_id) REFERENCES instruments(id),
    CONSTRAINT uq_pos_acct_instr UNIQUE (account_id, instrument_id)
);

CREATE TABLE settlements (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id    BIGINT        NOT NULL,
    instrument_id BIGINT,
    sim_date      DATE          NOT NULL,
    kind          VARCHAR(24)   NOT NULL,
    cash_flow     NUMERIC(19,4) NOT NULL,
    detail        VARCHAR(400),
    CONSTRAINT fk_settle_account FOREIGN KEY (account_id) REFERENCES accounts(id)
);

CREATE TABLE daily_bars (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT        NOT NULL,
    symbol     VARCHAR(80)   NOT NULL,
    sim_date   DATE          NOT NULL,
    open_px    NUMERIC(19,6) NOT NULL,
    high_px    NUMERIC(19,6) NOT NULL,
    low_px     NUMERIC(19,6) NOT NULL,
    close_px   NUMERIC(19,6) NOT NULL,
    CONSTRAINT uq_bar UNIQUE (session_id, symbol, sim_date)
);

CREATE TABLE equity_snapshots (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT        NOT NULL,
    sim_date   DATE          NOT NULL,
    equity     NUMERIC(19,4) NOT NULL,
    CONSTRAINT uq_snap UNIQUE (account_id, sim_date)
);

CREATE TABLE cohorts (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(120)  NOT NULL,
    instructor_id    BIGINT        NOT NULL,
    scenario_id      BIGINT        NOT NULL,
    session_id       BIGINT        NOT NULL,
    starting_balance NUMERIC(19,4) NOT NULL,
    join_code        VARCHAR(12)   NOT NULL,
    created_at       TIMESTAMP     NOT NULL,
    CONSTRAINT uq_cohort_code UNIQUE (join_code),
    CONSTRAINT fk_cohort_instr FOREIGN KEY (instructor_id) REFERENCES users(id)
);

CREATE TABLE cohort_members (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cohort_id BIGINT NOT NULL,
    user_id   BIGINT NOT NULL,
    CONSTRAINT uq_cohort_member UNIQUE (cohort_id, user_id),
    CONSTRAINT fk_cm_cohort FOREIGN KEY (cohort_id) REFERENCES cohorts(id),
    CONSTRAINT fk_cm_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX ix_orders_account ON orders(account_id);
CREATE INDEX ix_orders_status ON orders(status);
CREATE INDEX ix_fills_order ON fills(order_id);
CREATE INDEX ix_positions_account ON positions(account_id);
CREATE INDEX ix_settle_account ON settlements(account_id);
CREATE INDEX ix_bars_lookup ON daily_bars(session_id, symbol);
CREATE INDEX ix_instr_session ON instruments(session_id);
