-- Paper Desk core schema. Written to run on both Oracle 19c+/23ai and H2 (MODE=Oracle).

CREATE TABLE users (
    id            NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR2(255) NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    display_name  VARCHAR2(120) NOT NULL,
    role          VARCHAR2(20)  NOT NULL,
    created_at    TIMESTAMP     NOT NULL,
    CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE TABLE scenarios (
    id           NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR2(80)  NOT NULL,
    description  VARCHAR2(400),
    seed         NUMBER(19)    NOT NULL,
    acceleration NUMBER(12,2)  NOT NULL,
    params_json  CLOB          NOT NULL,
    CONSTRAINT uq_scenarios_name UNIQUE (name)
);

CREATE TABLE scenario_sessions (
    id               NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scenario_id      NUMBER(19)   NOT NULL,
    cohort_id        NUMBER(19),
    state            VARCHAR2(20) NOT NULL,
    sim_start        TIMESTAMP    NOT NULL,
    current_sim_time TIMESTAMP    NOT NULL,
    acceleration     NUMBER(12,2) NOT NULL,
    created_at       TIMESTAMP    NOT NULL,
    CONSTRAINT fk_sess_scenario FOREIGN KEY (scenario_id) REFERENCES scenarios(id)
);

CREATE TABLE instruments (
    id                 NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id         NUMBER(19)    NOT NULL,
    symbol             VARCHAR2(80)  NOT NULL,
    name               VARCHAR2(160) NOT NULL,
    instrument_type    VARCHAR2(20)  NOT NULL,
    underlying_id      NUMBER(19),
    strike             NUMBER(19,6),
    expiry_date        DATE,
    call_put           VARCHAR2(4),
    contract_size      NUMBER(19,4)  NOT NULL,
    initial_margin     NUMBER(19,4),
    maintenance_margin NUMBER(19,4),
    notional           NUMBER(19,2),
    fixed_rate         NUMBER(12,8),
    pay_freq_months    NUMBER(4),
    term_months        NUMBER(4),
    active             NUMBER(1)     NOT NULL,
    CONSTRAINT fk_instr_session FOREIGN KEY (session_id) REFERENCES scenario_sessions(id),
    CONSTRAINT fk_instr_under FOREIGN KEY (underlying_id) REFERENCES instruments(id),
    CONSTRAINT uq_instr_symbol UNIQUE (session_id, symbol)
);

CREATE TABLE accounts (
    id               NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          NUMBER(19)   NOT NULL,
    session_id       NUMBER(19)   NOT NULL,
    cash_balance     NUMBER(19,4) NOT NULL,
    margin_held      NUMBER(19,4) NOT NULL,
    starting_balance NUMBER(19,4) NOT NULL,
    created_at       TIMESTAMP    NOT NULL,
    CONSTRAINT fk_acct_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_acct_session FOREIGN KEY (session_id) REFERENCES scenario_sessions(id),
    CONSTRAINT uq_acct_user_session UNIQUE (user_id, session_id)
);

CREATE TABLE orders (
    id              NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id      NUMBER(19)   NOT NULL,
    instrument_id   NUMBER(19)   NOT NULL,
    side            VARCHAR2(4)  NOT NULL,
    order_type      VARCHAR2(10) NOT NULL,
    limit_price     NUMBER(19,6),
    qty             NUMBER(19,4) NOT NULL,
    status          VARCHAR2(12) NOT NULL,
    view_context    VARCHAR2(10),
    reject_reason   VARCHAR2(200),
    placed_sim_time TIMESTAMP    NOT NULL,
    CONSTRAINT fk_ord_account FOREIGN KEY (account_id) REFERENCES accounts(id),
    CONSTRAINT fk_ord_instr FOREIGN KEY (instrument_id) REFERENCES instruments(id)
);

CREATE TABLE fills (
    id            NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id      NUMBER(19)   NOT NULL,
    price         NUMBER(19,6) NOT NULL,
    qty           NUMBER(19,4) NOT NULL,
    fill_sim_time TIMESTAMP    NOT NULL,
    CONSTRAINT fk_fill_order FOREIGN KEY (order_id) REFERENCES orders(id)
);

CREATE TABLE positions (
    id                NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id        NUMBER(19)   NOT NULL,
    instrument_id     NUMBER(19)   NOT NULL,
    qty               NUMBER(19,4) NOT NULL,
    avg_price         NUMBER(19,6) NOT NULL,
    realized_pnl      NUMBER(19,4) NOT NULL,
    last_settle_price NUMBER(19,6),
    opened_sim_time   TIMESTAMP    NOT NULL,
    CONSTRAINT fk_pos_account FOREIGN KEY (account_id) REFERENCES accounts(id),
    CONSTRAINT fk_pos_instr FOREIGN KEY (instrument_id) REFERENCES instruments(id),
    CONSTRAINT uq_pos_acct_instr UNIQUE (account_id, instrument_id)
);

CREATE TABLE settlements (
    id            NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id    NUMBER(19)   NOT NULL,
    instrument_id NUMBER(19),
    sim_date      DATE         NOT NULL,
    kind          VARCHAR2(24) NOT NULL,
    cash_flow     NUMBER(19,4) NOT NULL,
    detail        VARCHAR2(400),
    CONSTRAINT fk_settle_account FOREIGN KEY (account_id) REFERENCES accounts(id)
);

CREATE TABLE daily_bars (
    id         NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id NUMBER(19)   NOT NULL,
    symbol     VARCHAR2(80) NOT NULL,
    sim_date   DATE         NOT NULL,
    open_px    NUMBER(19,6) NOT NULL,
    high_px    NUMBER(19,6) NOT NULL,
    low_px     NUMBER(19,6) NOT NULL,
    close_px   NUMBER(19,6) NOT NULL,
    CONSTRAINT uq_bar UNIQUE (session_id, symbol, sim_date)
);

CREATE TABLE equity_snapshots (
    id         NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id NUMBER(19)   NOT NULL,
    sim_date   DATE         NOT NULL,
    equity     NUMBER(19,4) NOT NULL,
    CONSTRAINT uq_snap UNIQUE (account_id, sim_date)
);

CREATE TABLE cohorts (
    id               NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR2(120) NOT NULL,
    instructor_id    NUMBER(19)    NOT NULL,
    scenario_id      NUMBER(19)    NOT NULL,
    session_id       NUMBER(19)    NOT NULL,
    starting_balance NUMBER(19,4)  NOT NULL,
    join_code        VARCHAR2(12)  NOT NULL,
    created_at       TIMESTAMP     NOT NULL,
    CONSTRAINT uq_cohort_code UNIQUE (join_code),
    CONSTRAINT fk_cohort_instr FOREIGN KEY (instructor_id) REFERENCES users(id)
);

CREATE TABLE cohort_members (
    id        NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cohort_id NUMBER(19) NOT NULL,
    user_id   NUMBER(19) NOT NULL,
    CONSTRAINT uq_cohort_member UNIQUE (cohort_id, user_id),
    CONSTRAINT fk_cm_cohort FOREIGN KEY (cohort_id) REFERENCES cohorts(id),
    CONSTRAINT fk_cm_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE INDEX ix_orders_account ON orders(account_id);
CREATE INDEX ix_orders_status ON orders(status);
CREATE INDEX ix_fills_order ON fills(order_id);
CREATE INDEX ix_positions_account ON positions(account_id);
CREATE INDEX ix_settle_account ON settlements(account_id);
CREATE INDEX ix_bars_lookup ON daily_bars(session_id, symbol);
CREATE INDEX ix_instr_session ON instruments(session_id);
