-- Gamification: per-account experience points and one-time achievement badges.

ALTER TABLE accounts ADD xp NUMERIC(19,4) DEFAULT 0 NOT NULL;

CREATE TABLE achievements (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT      NOT NULL,
    code       VARCHAR(40) NOT NULL,
    xp         INTEGER     NOT NULL,
    sim_date   DATE,
    created_at TIMESTAMP   NOT NULL,
    CONSTRAINT uq_achievement UNIQUE (account_id, code),
    CONSTRAINT fk_ach_account FOREIGN KEY (account_id) REFERENCES accounts(id)
);

CREATE INDEX ix_ach_account ON achievements(account_id);
