-- Gamification: per-account experience points and one-time achievement badges.

ALTER TABLE accounts ADD xp NUMBER(19,4) DEFAULT 0 NOT NULL;

CREATE TABLE achievements (
    id         NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id NUMBER(19)   NOT NULL,
    code       VARCHAR2(40) NOT NULL,
    xp         NUMBER(10)   NOT NULL,
    sim_date   DATE,
    created_at TIMESTAMP    NOT NULL,
    CONSTRAINT uq_achievement UNIQUE (account_id, code),
    CONSTRAINT fk_ach_account FOREIGN KEY (account_id) REFERENCES accounts(id)
);

CREATE INDEX ix_ach_account ON achievements(account_id);
