-- Guided missions: multi-step exercises completed once per account.

CREATE TABLE mission_completions (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id   BIGINT      NOT NULL,
    code         VARCHAR(40) NOT NULL,
    xp           INTEGER     NOT NULL,
    sim_date     DATE,
    created_at   TIMESTAMP   NOT NULL,
    CONSTRAINT uq_mission_completion UNIQUE (account_id, code),
    CONSTRAINT fk_mission_account FOREIGN KEY (account_id) REFERENCES accounts(id)
);

CREATE INDEX ix_mission_account ON mission_completions(account_id);
