-- Discrete closing-trade records for the trader scorecard (win rate, avg win/loss,
-- holding period). Position.realizedPnl is a running cumulative total and can't answer
-- "how did each individual closing trade do", so each closing/flip fill in
-- OrderService.applyFill() appends one row here alongside updating the position.
CREATE TABLE closed_trades (
    id              NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id      NUMBER(19)   NOT NULL,
    instrument_id   NUMBER(19)   NOT NULL,
    opened_sim_time TIMESTAMP    NOT NULL,
    closed_sim_time TIMESTAMP    NOT NULL,
    qty             NUMBER(19,4) NOT NULL,
    realized_pnl    NUMBER(19,4) NOT NULL,
    CONSTRAINT fk_closed_trade_account FOREIGN KEY (account_id) REFERENCES accounts(id),
    CONSTRAINT fk_closed_trade_instr FOREIGN KEY (instrument_id) REFERENCES instruments(id)
);

CREATE INDEX ix_closed_trade_account ON closed_trades(account_id);
