-- Instructor grading & feedback: a rubric-based grade per student per cohort,
-- and inline comments an instructor can leave on a specific trade.

CREATE TABLE cohort_grades (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cohort_id              BIGINT        NOT NULL,
    account_id             BIGINT        NOT NULL,
    instructor_id          BIGINT        NOT NULL,
    risk_management_score  INTEGER       NOT NULL,
    discipline_score       INTEGER       NOT NULL,
    diversification_score  INTEGER       NOT NULL,
    overall_score          INTEGER       NOT NULL,
    feedback               VARCHAR(2000),
    created_at             TIMESTAMP     NOT NULL,
    updated_at             TIMESTAMP     NOT NULL,
    CONSTRAINT uq_cohort_grade UNIQUE (cohort_id, account_id),
    CONSTRAINT fk_grade_cohort FOREIGN KEY (cohort_id) REFERENCES cohorts(id),
    CONSTRAINT fk_grade_account FOREIGN KEY (account_id) REFERENCES accounts(id)
);

CREATE TABLE trade_comments (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id      BIGINT        NOT NULL,
    account_id    BIGINT        NOT NULL,
    instructor_id BIGINT        NOT NULL,
    comment       VARCHAR(2000) NOT NULL,
    created_at    TIMESTAMP     NOT NULL,
    CONSTRAINT fk_comment_order FOREIGN KEY (order_id) REFERENCES orders(id),
    CONSTRAINT fk_comment_account FOREIGN KEY (account_id) REFERENCES accounts(id)
);

CREATE INDEX ix_grade_cohort ON cohort_grades(cohort_id);
CREATE INDEX ix_comment_order ON trade_comments(order_id);
