-- Timed challenges: instructor-initiated sprints scoped to a cohort, with
-- their own equity-since-challenge-start leaderboard, layered on top of the
-- always-on cohort leaderboard. "Active" is derived at read time (challenge
-- session's current sim date vs end_sim_date) rather than stored, so there's
-- no background job needed to close a challenge out.

CREATE TABLE challenges (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cohort_id         BIGINT        NOT NULL,
    name              VARCHAR(120)  NOT NULL,
    duration_sim_days INTEGER       NOT NULL,
    start_sim_date    DATE          NOT NULL,
    end_sim_date      DATE          NOT NULL,
    created_at        TIMESTAMP     NOT NULL,
    CONSTRAINT fk_challenge_cohort FOREIGN KEY (cohort_id) REFERENCES cohorts(id)
);

-- One row per student enrolled when the challenge was created (enrollment is
-- a snapshot -- students who join the cohort later don't retroactively join
-- an in-flight sprint, matching how a real trading competition works).
CREATE TABLE challenge_entries (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    challenge_id     BIGINT        NOT NULL,
    account_id       BIGINT        NOT NULL,
    starting_equity  NUMERIC(19,4) NOT NULL,
    CONSTRAINT uq_challenge_entry UNIQUE (challenge_id, account_id),
    CONSTRAINT fk_entry_challenge FOREIGN KEY (challenge_id) REFERENCES challenges(id),
    CONSTRAINT fk_entry_account FOREIGN KEY (account_id) REFERENCES accounts(id)
);

CREATE INDEX ix_challenge_cohort ON challenges(cohort_id);
CREATE INDEX ix_entry_challenge ON challenge_entries(challenge_id);
