-- Guided curricula: an instructor sequences existing missions (see the
-- Mission enum) into an ordered, assignable syllabus for a cohort. Steps
-- reference mission codes rather than duplicating title/description/xp --
-- those stay defined once in the Mission enum.

CREATE TABLE curricula (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cohort_id   BIGINT       NOT NULL,
    name        VARCHAR(120) NOT NULL,
    description VARCHAR(400),
    created_at  TIMESTAMP    NOT NULL,
    CONSTRAINT fk_curriculum_cohort FOREIGN KEY (cohort_id) REFERENCES cohorts(id)
);

CREATE TABLE curriculum_steps (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    curriculum_id BIGINT      NOT NULL,
    mission_code  VARCHAR(40) NOT NULL,
    step_order    INTEGER     NOT NULL,
    CONSTRAINT uq_curriculum_step UNIQUE (curriculum_id, step_order),
    CONSTRAINT fk_step_curriculum FOREIGN KEY (curriculum_id) REFERENCES curricula(id)
);

CREATE INDEX ix_curriculum_cohort ON curricula(cohort_id);
CREATE INDEX ix_step_curriculum ON curriculum_steps(curriculum_id);
